#!/usr/bin/env python3
"""
Add the machine-readable layer: structured data, share cards, llms.txt.

    python3 tools/seo-inject.py

Run AFTER prerender.py, which rewrites each page wholesale and would otherwise
discard this. Idempotent — it strips its own previous output before writing, so
running it twice is the same as running it once.

Three things go in:

  1. JSON-LD. A single @graph per page, so the Organization is declared once and
     every page points at the same @id. Search engines and AI answer engines both
     use this to decide what entity a site is *about*; without it they infer from
     prose, and infer worse. Every value here is also visible on the page — that
     is a hard requirement of Google's structured data policy, not a style note.
  2. og:image / twitter:card, so a shared link renders as a card rather than a
     bare URL. The image is generated by tools/make-og-image.sh.
  3. llms.txt, the convention AI crawlers increasingly look for: one markdown
     summary of what the company is and where the real pages are.

It also strips a stray <html lang> click listener if one is still present.
Read the note above LANG_SCRIPT before acting on that: the sentence that used
to stand here — that the switcher has no translations behind it — was false,
and removing the listener on the strength of it broke the site.
"""

import json
import re
import sys
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CO = json.loads((ROOT / "content/company.json").read_text(encoding="utf-8"))
# Only the locales that actually have pages on disk. The Chinese and Arabic
# trees are derived by tools/localise.py, which is not currently in the
# pipeline — see its docstring. Declaring hreflang for a locale that 404s is
# worse than declaring none.
LOCALES = ["en"] + [c for c in ("zh", "ar") if (ROOT / c / "index.html").exists()]
L = {c: json.loads((ROOT / f"content/i18n/{c}.json").read_text(encoding="utf-8"))
     for c in LOCALES}
EN = L["en"]

SITE = CO["siteUrl"]
ORG = f"{SITE}/#organization"
WEB = f"{SITE}/#website"

MARK = "<!-- seo-inject -->"
END = "<!-- /seo-inject -->"

PAGES = {
    "": ("WebPage", "home"),
    "solutions": ("CollectionPage", "solutions"),
    "about": ("AboutPage", "about"),
    "contact": ("ContactPage", "contact"),
    "privacy": ("WebPage", "privacy"),
    "terms": ("WebPage", "terms"),
}

lat, lon = [c.strip() for c in CO["coordinates"].split(",")]
addr = CO["address"]["en"]


# Built by tools/build-faq.py with a head of its own. Listed for discovery,
# but never head-injected — doing so would overwrite its FAQPage markup.
EXTRA = ["faq"]


def page_url(locale, slug):
    root = f"{SITE}/" if locale == "en" else f"{SITE}/{locale}/"
    return root if not slug else f"{root}{slug}/"


def organisation():
    lic = CO["licence"]
    org = {
        "@type": "Organization",
        "@id": ORG,
        "name": CO["brand"],
        "legalName": CO["legalName"]["en"],
        "alternateName": CO["legalName"]["ar"],
        "url": f"{SITE}/",
        "description": EN["home"]["description"],
        "slogan": EN["home"]["hero"]["heading"].rstrip("."),
        "foundingDate": "2026-08-20",
        "email": CO["email"]["general"],
        "logo": {
            "@type": "ImageObject",
            "url": f"{SITE}/assets/img/logo/logo-horizontal.png",
            "width": 474, "height": 90,
        },
        "image": f"{SITE}/assets/img/og-image.png",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": ", ".join(addr["lines"][:2]),
            "addressLocality": "Dubai",
            "addressRegion": "Dubai",
            "addressCountry": "AE",
        },
        "location": {
            "@type": "Place",
            "address": {"@type": "PostalAddress", "streetAddress": addr["full"]},
            "geo": {"@type": "GeoCoordinates", "latitude": float(lat), "longitude": float(lon)},
        },
        # Registry numbers printed on the trade licence and shown on /about/.
        # These are what a verifier cross-checks the company against.
        "identifier": [
            {"@type": "PropertyValue", "name": "Dubai commercial licence", "value": lic["number"]},
            {"@type": "PropertyValue", "name": "Commercial register number", "value": lic["registerNumber"]},
            {"@type": "PropertyValue", "name": "Dubai Chamber membership", "value": lic["chamberNumber"]},
        ],
        "areaServed": [
            {"@type": "Country", "name": "United Arab Emirates"},
            {"@type": "Place", "name": "Gulf Cooperation Council"},
        ],
        "knowsLanguage": ["en", "ar", "zh"],
        "contactPoint": [
            {"@type": "ContactPoint", "contactType": "sales", "email": CO["email"]["general"],
             "availableLanguage": ["English", "Arabic", "Chinese"]},
            {"@type": "ContactPoint", "contactType": "technical support", "email": CO["email"]["support"],
             "availableLanguage": ["English", "Arabic", "Chinese"]},
        ],
        "hasOfferCatalog": {
            "@type": "OfferCatalog",
            "name": "Solutions",
            "itemListElement": [
                {"@type": "Offer", "itemOffered": {
                    "@type": "Service", "name": item["title"], "description": item["summary"],
                    "provider": {"@id": ORG},
                }}
                for item in EN["home"]["pillars"]["items"]
            ],
        },
    }
    # schema.org has a dedicated property for it, which is what a parser
    # reads; repeating it in `identifier` would state the same fact twice.
    # Emitted only once tools/duns.py has put it on /about/ — every value
    # here needs a visible counterpart on the page.
    if CO.get("dunsNumber"):
        org["duns"] = CO["dunsNumber"]
    return org


def website():
    return {
        "@type": "WebSite", "@id": WEB, "url": f"{SITE}/",
        "name": CO["brand"], "inLanguage": LOCALES,
        "publisher": {"@id": ORG},
    }


def webpage(locale, slug, kind):
    url = page_url(locale, slug)
    t = L[locale]
    meta = t[PAGES[slug][1]]
    crumbs = [{"@type": "ListItem", "position": 1, "name": t["nav"]["home"],
               "item": page_url(locale, "")}]
    if slug:
        crumbs.append({"@type": "ListItem", "position": 2,
                       "name": t["nav"].get(PAGES[slug][1], slug.title()), "item": url})
    return {
        "@type": kind, "@id": f"{url}#webpage", "url": url,
        "name": meta["title"], "description": meta["description"],
        "isPartOf": {"@id": WEB}, "about": {"@id": ORG},
        "inLanguage": t["meta"]["htmlLang"],
        "primaryImageOfPage": {"@type": "ImageObject", "url": f"{SITE}/assets/img/og-image.png"},
        "breadcrumb": {"@type": "BreadcrumbList", "itemListElement": crumbs},
    }


def head_block(locale, slug):
    kind, key = PAGES[slug]
    meta = L[locale][key]
    url = page_url(locale, slug)
    graph = {"@context": "https://schema.org",
             "@graph": [organisation(), website(), webpage(locale, slug, kind)]}
    ld = json.dumps(graph, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    esc = lambda s: s.replace("&", "&amp;").replace('"', "&quot;")
    # Every language version points at every other, and each is its own
    # canonical. Without this the three read as duplicates of one page.
    alts = [f'<link rel="alternate" hreflang="{L[c]["meta"]["htmlLang"]}" '
            f'href="{page_url(c, slug)}">' for c in LOCALES]
    alts.append(f'<link rel="alternate" hreflang="x-default" href="{page_url("en", slug)}">')

    return "\n".join([
        MARK,
        '<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">',
        f'<link rel="canonical" href="{url}">',
        f'<meta property="og:url" content="{url}">',
        *alts,
        f'<meta property="og:image" content="{SITE}/assets/img/og-image.png">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{esc(EN["home"]["hero"]["heading"])}">',
        f'<meta property="og:locale" content="{L[locale]["meta"]["htmlLang"]}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{esc(meta["title"])}">',
        f'<meta name="twitter:description" content="{esc(meta["description"])}">',
        f'<meta name="twitter:image" content="{SITE}/assets/img/og-image.png">',
        f'<link rel="alternate" type="text/plain" href="{SITE}/llms.txt" title="llms.txt">',
        f'<script type="application/ld+json">{ld}</script>',
        END,
    ])


# A stray listener that rewrote <html lang> on button click. It was added on
# the conclusion that the switcher was decorative — a conclusion produced by
# grepping a JSON-encoded template for Chinese, which always returns zero
# because JSON escapes non-ASCII as \uXXXX. The runtime has always carried a
# full DICT for zh and ar; see docs/verified-behaviour.md. Language now lives
# in the URL (tools/lang-urls.py) and no page matches this pattern any more,
# so the strip is a no-op, kept only in case a re-export brings it back.
LANG_SCRIPT = re.compile(r'<script>\(function\(\)\{var m=\{"EN".*?</script>\s*', re.S)


TEMPLATE = re.compile(r'(<script type="__bundler/template">)(.*?)(</script>)', re.S)

# Tags this block re-declares. Left in place they would appear twice, and for
# canonical and og:url the inherited value is the English URL — the thing being
# corrected.
SUPERSEDED = re.compile(
    r'\s*<(?:link rel="canonical"|meta property="og:url"|meta property="og:locale")[^>]*>')


def strip_ours(doc):
    return SUPERSEDED.sub("", re.sub(re.escape(MARK) + r".*?" + re.escape(END) + r"\s*",
                                     "", doc, flags=re.S))


def inject_template(html, locale, slug):
    """Put the same block inside the template.

    The served <head> is not what a rendering crawler ends up reading. The
    bundle replaces the whole document element on load, so everything written
    here is gone from the DOM by the time the page is interactive, and the
    template's own head takes over — a head that was copied from the English
    page and still says so. Measured on /zh/about/ before this existed: zero
    ld+json, zero hreflang, and rel=canonical pointing at /about/, which tells
    a crawler the Chinese page is a duplicate of the English one.

    Non-rendering crawlers read the served HTML and were always fine. Googlebot
    renders. Both need the block, so both get it.

    Re-encoding escapes "</" — the template holds a nested </script> and the
    JSON-LD adds another, and leaving either literal ends the enclosing script
    element early and truncates the page.
    """
    match = TEMPLATE.search(html)
    if not match:
        return html, False
    template = json.loads(match.group(2))
    if "</head>" not in template:
        return html, False
    template = strip_ours(template)
    template = template.replace("</head>", head_block(locale, slug) + "\n</head>", 1)
    encoded = json.dumps(template, ensure_ascii=False).replace("</", "<\\/")
    return html[:match.start(2)] + encoded + html[match.end(2):], True


def inject(path, locale, slug):
    html = path.read_text(encoding="utf-8")
    # prepare-export.py writes its own canonical and og:url for the English
    # page; the localised copies inherit them verbatim, which points zh and ar
    # at the English URL. Ours replace them.
    html = strip_ours(html)
    html, dropped = LANG_SCRIPT.subn("", html)
    html = html.replace("</head>", head_block(locale, slug) + "\n</head>", 1)
    html, in_template = inject_template(html, locale, slug)
    path.write_text(html, encoding="utf-8")
    return dropped, in_template


def llms_txt():
    h = EN["home"]
    lines = [
        f"# {CO['brand']}", "",
        f"> {h['hero']['lede']}", "",
        f"{CO['legalName']['en']} is a technology company registered in Dubai, United Arab "
        f"Emirates, holding commercial licence {CO['licence']['number']} issued by the "
        f"{CO['licence']['authority']['en']}. It serves enterprise clients across the UAE, the "
        f"wider GCC and Greater China, and delivers in English, Arabic and Chinese.", "",
        "## Lines of business", "",
    ]
    for item in h["pillars"]["items"]:
        lines.append(f"### {item['title']}")
        lines.append("")
        lines.append(item["summary"])
        lines.append("")
        for p in item["points"]:
            lines.append(f"- {p}")
        lines.append("")

    lines += ["## Pages", ""]
    for slug in PAGES:
        key = PAGES[slug][1]
        lines.append(f"- [{EN[key]['title']}]({page_url('en', slug)}): {EN[key]['description']}")
    faq = json.loads((ROOT / "content/faq.json").read_text(encoding="utf-8"))["en"]
    lines.append(f"- [{faq['title']}]({page_url('en', 'faq')}): {faq['description']}")

    others = [c for c in ("zh", "ar") if c in L]
    if others:
        lines += ["", "## Other languages", "",
                  "The same pages are published in these languages. The Arabic "
                  "version is laid out right-to-left.", ""]
        for c in others:
            lines.append(f"- {L[c]['meta']['label']}: {page_url(c, '')}")

    lines += [
        "", "## Contact", "",
        f"- Enquiries and new projects: {CO['email']['general']}",
        f"- Technical support: {CO['email']['support']}",
        f"- Registered address: {addr['full']}",
        f"- Business hours: {CO['hours']['en']}",
        "",
    ]
    (ROOT / "llms.txt").write_text("\n".join(lines), encoding="utf-8")
    return len("\n".join(lines))


def build_date():
    """Date of the last commit — a real content-change signal, unlike build time.

    <lastmod> stamped with "now" on every build is noise, and Google ignores a
    lastmod it has learned not to trust.
    """
    try:
        out = subprocess.run(["git", "log", "-1", "--format=%cs"], cwd=ROOT,
                             capture_output=True, text=True, timeout=10)
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip()
    except Exception:
        pass
    return None


def finalise_sitemap():
    """Rewrite the sitemap across all three languages.

    prepare-export.py only knows about the English pages. Each entry declares
    its alternates, which is how a crawler learns the three are one page in
    three languages rather than three thin pages.
    """
    stamp = build_date()
    rows = []
    for locale in LOCALES:
        for slug in list(PAGES) + [e for e in EXTRA if (ROOT / (
                f"{e}/index.html" if locale == "en" else f"{locale}/{e}/index.html")).exists()]:
            alts = "\n".join(
                f'    <xhtml:link rel="alternate" hreflang="{L[c]["meta"]["htmlLang"]}"'
                f' href="{page_url(c, slug)}"/>' for c in LOCALES)
            rows.append(
                "  <url>\n"
                f"    <loc>{page_url(locale, slug)}</loc>\n"
                + (f"    <lastmod>{stamp}</lastmod>\n" if stamp else "")
                + f"{alts}\n"
                f"    <changefreq>monthly</changefreq>\n"
                f"    <priority>{'1.0' if not slug else '0.7'}</priority>\n"
                "  </url>")
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
        + "\n".join(rows) + "\n</urlset>\n", encoding="utf-8")
    return stamp, len(rows)


def robots_txt():
    """Permissive, and explicit about it.

    "User-agent: * Allow: /" already permits every crawler, so naming the AI
    ones changes no behaviour — it records the decision, so that a later "should
    we block GPTBot?" is answered by the file rather than by guesswork. The
    llms.txt pointer is the part that does real work.
    """
    agents = ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "Claude-User",
              "Claude-SearchBot", "PerplexityBot", "Perplexity-User",
              "Google-Extended", "Applebot", "Applebot-Extended", "Bingbot"]
    lines = ["User-agent: *", "Allow: /", ""]
    for a in agents:
        lines += [f"User-agent: {a}", "Allow: /", ""]
    lines += [f"Sitemap: {SITE}/sitemap.xml", f"# Plain-language site summary: {SITE}/llms.txt", ""]
    (ROOT / "robots.txt").write_text("\n".join(lines), encoding="utf-8")
    return len(agents)


def main():
    print(f"\n  {'locale':<8} {'page':<12}   status")
    print("  " + "-" * 34)
    n, templated = 0, 0
    for locale in LOCALES:
        done = 0
        for slug in PAGES:
            rel = f"{slug}/index.html" if slug else "index.html"
            path = ROOT / (rel if locale == "en" else f"{locale}/{rel}")
            _, in_template = inject(path, locale, slug)
            done += in_template
            n += 1
        templated += done
        print(f"  {locale:<8} {'(' + str(len(PAGES)) + ' pages)':<12}   ok, {done}/{len(PAGES)} in template")
    if templated != n:
        sys.exit(f"\n  Only {templated}/{n} templates took the block — a page is shaped "
                 "differently and its rendered head would keep the English canonical.\n")
    size = llms_txt()
    print(f"\n  {n} pages total")
    stamp, urls = finalise_sitemap()
    agents = robots_txt()
    print(f"  llms.txt    {size:,} bytes")
    print(f"  sitemap     {urls} URLs, lastmod {stamp or '(none)'}")
    print(f"  robots.txt  {agents} AI crawlers named explicitly\n")


if __name__ == "__main__":
    main()
