#!/usr/bin/env python3
"""
Add the machine-readable layer: structured data, share cards, llms.txt.

    python3 tools/seo-inject.py

Run AFTER prerender.py, which rewrites each page wholesale and would otherwise
discard this. Idempotent — it strips its own previous output before writing, so
running it twice is the same as running it once.

Three things go in:

  1. JSON-LD. A single @graph per page, so the Organization is declared once and
     every page points at the same @id. Search engines and AI answer engines both
     use this to decide what entity a site is *about*; without it they infer from
     prose, and infer worse. Every value here is also visible on the page — that
     is a hard requirement of Google's structured data policy, not a style note.
  2. og:image / twitter:card, so a shared link renders as a card rather than a
     bare URL. The image is generated by tools/make-og-image.sh.
  3. llms.txt, the convention AI crawlers increasingly look for: one markdown
     summary of what the company is and where the real pages are.

It also removes the export's language-switch listener. The switcher has no
translations behind it — the buttons only set <html lang>, so clicking 中文
labelled English prose as Chinese. A wrong lang attribute is worse than none.
"""

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CO = json.loads((ROOT / "content/company.json").read_text(encoding="utf-8"))
EN = json.loads((ROOT / "content/i18n/en.json").read_text(encoding="utf-8"))

SITE = CO["siteUrl"]
ORG = f"{SITE}/#organization"
WEB = f"{SITE}/#website"

MARK = "<!-- seo-inject -->"
END = "<!-- /seo-inject -->"

PAGES = {
    "": ("WebPage", "home"),
    "solutions": ("CollectionPage", "solutions"),
    "about": ("AboutPage", "about"),
    "contact": ("ContactPage", "contact"),
    "privacy": ("WebPage", "privacy"),
    "terms": ("WebPage", "terms"),
}

lat, lon = [c.strip() for c in CO["coordinates"].split(",")]
addr = CO["address"]["en"]


def organisation():
    lic = CO["licence"]
    return {
        "@type": "Organization",
        "@id": ORG,
        "name": CO["brand"],
        "legalName": CO["legalName"]["en"],
        "alternateName": CO["legalName"]["ar"],
        "url": f"{SITE}/",
        "description": EN["home"]["description"],
        "slogan": EN["home"]["hero"]["heading"].rstrip("."),
        "foundingDate": "2026-08-20",
        "email": CO["email"]["general"],
        "logo": {
            "@type": "ImageObject",
            "url": f"{SITE}/assets/img/logo/logo-horizontal.png",
            "width": 474, "height": 90,
        },
        "image": f"{SITE}/assets/img/og-image.png",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": ", ".join(addr["lines"][:2]),
            "addressLocality": "Dubai",
            "addressRegion": "Dubai",
            "addressCountry": "AE",
        },
        "location": {
            "@type": "Place",
            "address": {"@type": "PostalAddress", "streetAddress": addr["full"]},
            "geo": {"@type": "GeoCoordinates", "latitude": float(lat), "longitude": float(lon)},
        },
        # Registry numbers printed on the trade licence and shown on /about/.
        # These are what a verifier cross-checks the company against.
        "identifier": [
            {"@type": "PropertyValue", "name": "Dubai commercial licence", "value": lic["number"]},
            {"@type": "PropertyValue", "name": "Commercial register number", "value": lic["registerNumber"]},
            {"@type": "PropertyValue", "name": "Dubai Chamber membership", "value": lic["chamberNumber"]},
        ],
        "areaServed": [
            {"@type": "Country", "name": "United Arab Emirates"},
            {"@type": "Place", "name": "Gulf Cooperation Council"},
        ],
        "knowsLanguage": ["en", "ar", "zh"],
        "contactPoint": [
            {"@type": "ContactPoint", "contactType": "sales", "email": CO["email"]["general"],
             "availableLanguage": ["English", "Arabic", "Chinese"]},
            {"@type": "ContactPoint", "contactType": "technical support", "email": CO["email"]["support"],
             "availableLanguage": ["English", "Arabic", "Chinese"]},
        ],
        "hasOfferCatalog": {
            "@type": "OfferCatalog",
            "name": "Solutions",
            "itemListElement": [
                {"@type": "Offer", "itemOffered": {
                    "@type": "Service", "name": item["title"], "description": item["summary"],
                    "provider": {"@id": ORG},
                }}
                for item in EN["home"]["pillars"]["items"]
            ],
        },
    }


def website():
    return {
        "@type": "WebSite", "@id": WEB, "url": f"{SITE}/",
        "name": CO["brand"], "inLanguage": "en",
        "publisher": {"@id": ORG},
    }


def webpage(slug, kind):
    url = f"{SITE}/{slug + '/' if slug else ''}"
    meta = EN[PAGES[slug][1]]
    crumbs = [{"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"}]
    if slug:
        crumbs.append({"@type": "ListItem", "position": 2,
                       "name": EN["nav"].get(PAGES[slug][1], slug.title()), "item": url})
    return {
        "@type": kind, "@id": f"{url}#webpage", "url": url,
        "name": meta["title"], "description": meta["description"],
        "isPartOf": {"@id": WEB}, "about": {"@id": ORG},
        "inLanguage": "en", "primaryImageOfPage": {"@type": "ImageObject", "url": f"{SITE}/assets/img/og-image.png"},
        "breadcrumb": {"@type": "BreadcrumbList", "itemListElement": crumbs},
    }


def head_block(slug):
    kind, key = PAGES[slug]
    meta = EN[key]
    url = f"{SITE}/{slug + '/' if slug else ''}"
    graph = {"@context": "https://schema.org",
             "@graph": [organisation(), website(), webpage(slug, kind)]}
    ld = json.dumps(graph, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    esc = lambda s: s.replace("&", "&amp;").replace('"', "&quot;")
    return "\n".join([
        MARK,
        '<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">',
        f'<meta property="og:image" content="{SITE}/assets/img/og-image.png">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{esc(EN["home"]["hero"]["heading"])}">',
        '<meta property="og:locale" content="en">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{esc(meta["title"])}">',
        f'<meta name="twitter:description" content="{esc(meta["description"])}">',
        f'<meta name="twitter:image" content="{SITE}/assets/img/og-image.png">',
        f'<link rel="alternate" type="text/plain" href="{SITE}/llms.txt" title="llms.txt">',
        f'<script type="application/ld+json">{ld}</script>',
        END,
    ])


# The export ships a click listener that rewrites <html lang> to zh-Hans or ar
# when the language buttons are pressed. There is no translated copy behind them.
LANG_SCRIPT = re.compile(r'<script>\(function\(\)\{var m=\{"EN".*?</script>\s*', re.S)


def inject(path, slug):
    html = path.read_text(encoding="utf-8")
    html = re.sub(re.escape(MARK) + r".*?" + re.escape(END) + r"\s*", "", html, flags=re.S)
    html, dropped = LANG_SCRIPT.subn("", html)
    html = html.replace("</head>", head_block(slug) + "\n</head>", 1)
    path.write_text(html, encoding="utf-8")
    return dropped


def llms_txt():
    h = EN["home"]
    lines = [
        f"# {CO['brand']}", "",
        f"> {h['hero']['lede']}", "",
        f"{CO['legalName']['en']} is a technology company registered in Dubai, United Arab "
        f"Emirates, holding commercial licence {CO['licence']['number']} issued by the "
        f"{CO['licence']['authority']['en']}. It serves enterprise clients across the UAE, the "
        f"wider GCC and Greater China, and delivers in English, Arabic and Chinese.", "",
        "## Lines of business", "",
    ]
    for item in h["pillars"]["items"]:
        lines.append(f"### {item['title']}")
        lines.append("")
        lines.append(item["summary"])
        lines.append("")
        for p in item["points"]:
            lines.append(f"- {p}")
        lines.append("")

    lines += ["## Pages", ""]
    for slug in PAGES:
        key = PAGES[slug][1]
        url = f"{SITE}/{slug + '/' if slug else ''}"
        lines.append(f"- [{EN[key]['title']}]({url}): {EN[key]['description']}")

    lines += [
        "", "## Contact", "",
        f"- Enquiries and new projects: {CO['email']['general']}",
        f"- Technical support: {CO['email']['support']}",
        f"- Registered address: {addr['full']}",
        f"- Business hours: {CO['hours']['en']}",
        "",
    ]
    (ROOT / "llms.txt").write_text("\n".join(lines), encoding="utf-8")
    return len("\n".join(lines))


def build_date():
    """Date of the last commit — a real content-change signal, unlike build time.

    <lastmod> stamped with "now" on every build is noise, and Google ignores a
    lastmod it has learned not to trust.
    """
    try:
        out = subprocess.run(["git", "log", "-1", "--format=%cs"], cwd=ROOT,
                             capture_output=True, text=True, timeout=10)
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip()
    except Exception:
        pass
    return None


def finalise_sitemap():
    """Add <lastmod> to the sitemap prepare-export.py generated."""
    path = ROOT / "sitemap.xml"
    xml = path.read_text(encoding="utf-8")
    xml = re.sub(r"\s*<lastmod>[^<]*</lastmod>", "", xml)
    stamp = build_date()
    if stamp:
        xml = xml.replace("</loc>", f"</loc>\n    <lastmod>{stamp}</lastmod>", )
    path.write_text(xml, encoding="utf-8")
    return stamp


def robots_txt():
    """Permissive, and explicit about it.

    "User-agent: * Allow: /" already permits every crawler, so naming the AI
    ones changes no behaviour — it records the decision, so that a later "should
    we block GPTBot?" is answered by the file rather than by guesswork. The
    llms.txt pointer is the part that does real work.
    """
    agents = ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "Claude-User",
              "Claude-SearchBot", "PerplexityBot", "Perplexity-User",
              "Google-Extended", "Applebot", "Applebot-Extended", "Bingbot"]
    lines = ["User-agent: *", "Allow: /", ""]
    for a in agents:
        lines += [f"User-agent: {a}", "Allow: /", ""]
    lines += [f"Sitemap: {SITE}/sitemap.xml", f"# Plain-language site summary: {SITE}/llms.txt", ""]
    (ROOT / "robots.txt").write_text("\n".join(lines), encoding="utf-8")
    return len(agents)


def main():
    print(f"\n  {'page':<12} {'lang-script':>12}   status")
    print("  " + "-" * 40)
    for slug in PAGES:
        path = ROOT / (f"{slug}/index.html" if slug else "index.html")
        dropped = inject(path, slug)
        print(f"  {slug or '/':<12} {('removed' if dropped else '-'):>12}   ok")
    size = llms_txt()
    stamp = finalise_sitemap()
    agents = robots_txt()
    print(f"\n  llms.txt    {size:,} bytes")
    print(f"  sitemap     lastmod {stamp or '(no git date — omitted)'}")
    print(f"  robots.txt  {agents} AI crawlers named explicitly\n")


if __name__ == "__main__":
    main()
